config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root 'home#index'
  scope :cms, module: 'cms', path: 'cms' do
    resources :assets
    resources :layouts
    resources :pages
    resources :sites do
      get :edit_cms
      post :add_assets
      resources :messages
    end
    post 'custom-assets', to: 'assets#custom_asset'
  end
  match '*path', to: 'home#index', via: :all
end

app/models/site.rb
class Site < ApplicationRecord
  has_paper_trail
  has_many :layouts, dependent: :destroy
  has_many :pages,   dependent: :destroy
  has_many :assets,  dependent: :destroy

  validates :name, :description, :domain, presence: true

  attribute :initialize_with, :string

  def link_assets_from(framework)
    framework_files = Dir.entries(File.join('public', framework.downcase)).reject { |f| f.starts_with?('.') }

    framework_files.each do |file_path|
      full_path = File.join('public', framework.downcase, file_path)
      next unless File.exist?(full_path)

      create_asset(full_path)
    end

    if assets.count >= 1
      layout = create_default_layout
      create_default_page(layout)
    end
  end

  private

  def create_default_page(layout)
    page = Page.new
    page.site_id = id
    page.content = landing_page_template
    page.layout_id = layout.id
    page.name = 'index.html'
    page.save!
  end

  def create_default_layout
    layout = Layout.new
    layout.name = 'home.html'
    layout.site_id = id
    layout.content = layout_template
    layout.save!
    layout
  end

  def create_asset(full_path)
    asset = Asset.new
    asset.attachment = File.open(full_path)
    asset.site_id = id
    asset.save!
  end

  def landing_page_template
    <<~HTML
      <!-- home -->
      <div class='jumbotron'>
	      <h1>Sockem generated Site.</h1>
	      <p class="lead">
          This example is a quick exercise to illustrate how fixed to top navbar works. 
          As you scroll, it will remain fixed to the top of your browser's viewport.
  	    </p>
      </div>
    HTML
  end

  def layout_template
    <<~HTML
      <!doctype html>
        <html lang='en'>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <title>Sockem generated site using Bootstrap 4.0</title>

            {{ include_stylesheets }}  
            {{ include_javascripts }}
          </head>
          <body class='bg-light'>
            #{nav_bar}
            <main role="main" class="container">
              {{ page }}
            </main>
          </body>
        </html>
    HTML
  end

  def nav_bar
    <<~HTML
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">#{name}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
          </ul>
          <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    HTML
  end
end

app/controllers/cms/assets_controller.rb
module Cms
  class AssetsController < ApplicationController
    before_action :authenticate_admin!

    before_action :set_asset, only: [:show, :edit, :update, :destroy]

    # GET /assets
    # GET /assets.json
    def index
      @assets = Asset.all
    end

    # GET /assets/1
    # GET /assets/1.json
    def show
      respond_to do |format|
        format.html { redirect_to site_edit_cms_path(@asset.site) }
        format.js { render :show, status: 200 }
        format.json { render json: { name: @asset.name, content: @asset.attachment.file&.read || '', id: @asset.id } }
      end
    end

    # GET /assets/new
    def new
      @asset = Asset.new
    end

    # GET /assets/1/edit
    def edit; end

    # POST /assets
    # POST /assets.json
    def create
      @asset = Asset.new(asset_params)

      respond_to do |format|
        if @asset.save
          format.html { redirect_to @asset, notice: 'Asset was successfully created.' }
          format.json { render :show, status: :created, location: @asset }
        else
          format.html { render :new }
          format.json { render json: @asset.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /assets/1
    # PATCH/PUT /assets/1.json
    def update
      if content_asset_params[:content].present?
        file_name_array = content_asset_params[:name].split('.')
        file = Tempfile.new([file_name_array.first, ".#{file_name_array.last}"])
        file.write(content_asset_params[:content])
        file.rewind
        file.read
        @asset.attachment = File.open(file.path)
        @asset.save
        file.close
        file.unlink
      end
      @asset.update(asset_params)
      render json: { name: @asset.name, content: @asset.attachment.file&.read || '', id: @asset.id }
    end

    # DELETE /assets/1
    # DELETE /assets/1.json
    def destroy
      @asset.destroy
      respond_to do |format|
        format.html { redirect_to request.referer, notice: 'Asset was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def custom_asset
      @asset = Asset.find_or_initialize_by(
        {
          name: custom_asset_params[:name].strip.gsub('<br>', ''),
          site_id: custom_asset_params[:site_id]
        }
      )
      respond_to do |format|
        if @asset.update_attributes(custom_asset_params)
          format.json { render json: @asset, status: :created }
        else
          format.json { render json: @asset.errors, status: :unprocessable_entity }
        end
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_asset
      @asset = Asset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asset_params
      params.require(:asset).permit(:priority)
    end

    def custom_asset_params
      params.require(:asset).permit(:name, :site_id)
    end

    def content_asset_params
      params.require(:asset).permit(:content, :name)
    end
  end
end

app/controllers/cms/layouts_controller.rb
module Cms
  class LayoutsController < ApplicationController
    before_action :authenticate_admin!

    before_action :set_layout, only: [:show, :edit, :update, :destroy]

    # GET /layouts
    # GET /layouts.json
    def index
      @layouts = Layout.all
    end

    # GET /layouts/1
    # GET /layouts/1.json
    def show
      respond_to do |format|
        format.html { render json: { name: @layout.name, content: @layout.content, id: @layout.id } }
        format.js { render :show, status: 200 }
        format.json { render json: { name: @layout.name, content: @layout.content, id: @layout.id } }
      end
    end

    # GET /layouts/new
    def new
      @layout = Layout.new
    end

    # GET /layouts/1/edit
    def edit
    end

    # POST /layouts
    # POST /layouts.json
    def create
      @layout = Layout.find_or_initialize_by(
          name: layout_params[:name].strip.gsub('<br>', ''),
          site_id: layout_params[:site_id]
      )

      respond_to do |format|
        if @layout.update_attributes(layout_params)
          format.json { render json: @layout, status: :created }
        else
          format.json { render json: @layout.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /layouts/1
    # PATCH/PUT /layouts/1.json
    def update
      respond_to do |format|
        if @layout.update(layout_params)
          format.json { render json: @layout, status: :ok }
        else
          format.json { render json: @layout.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /layouts/1
    # DELETE /layouts/1.json
    def destroy
      @layout.destroy
      respond_to do |format|
        format.html { redirect_to layouts_url, notice: 'Layout was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_layout
      @layout = Layout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def layout_params
      params.require(:layout).permit(:name, :content, :site_id)
    end
  end
end

app/controllers/cms/messages_controller.rb
module Cms
  class MessagesController < ApplicationController
    include ActionController::RequestForgeryProtection
    protect_from_forgery with: :exception, unless: -> { request.format.json? }
    
    def index
      # TODO: Enable pagination and filter
      @messages = Message.where(site_id: params[:site_id])
      respond_to do |format|
        format.html
        format.json { render json: { data: @messages } }
      end
      # render json: @messages      
    end

    def create
      @message = Message.new(message_params)
      if @message.save
        render json: :ok, status: :created
      else
        render json: { errors: message.errors }, status: :unprocessable_entity
      end
    end

    private

    def message_params
      params.require(:message).permit(:first_name, :last_name, :site_id, :blob, :email, :content)
    end
  end
end

app/controllers/cms/pages_controller.rb
module Cms
  class PagesController < ApplicationController
    before_action :authenticate_admin!

    before_action :set_page, only: [:show, :edit, :update, :destroy]

    # GET /pages
    # GET /pages.json
    def index
      @pages = Page.all
    end

    # GET /pages/1
    # GET /pages/1.json
    def show
      respond_to do |format|
        format.js { render :show, status: 200 }
        format.json { render json: { name: @page.name, content: @page.content, id: @page.id } }
      end
    end

    # GET /pages/new
    def new
      @page = Page.new
    end

    # GET /pages/1/edit
    def edit; end

    # POST /pages
    # POST /pages.json
    def create
      @page = Page.find_or_initialize_by(
        name: page_params[:name].strip.gsub('<br>', ''),
        site_id: page_params[:site_id]
      )

      respond_to do |format|
        if @page.update_attributes(page_params)
          format.json { render json: @page, status: :created }
        else
          format.json { render json: @page.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /pages/1
    # PATCH/PUT /pages/1.json
    # NOTE to associate a page to a layout use a template tag as discussed with Abhi
    # {{ layout "LAYOUT_TO_USE" }}
    # on the top of every page.
    # This will be stripped out and saved every time a layout has to be changed
    # they have to add the above layout tag. And it will read it and update
    def update
      respond_to do |format|
        if @page.update(page_params)
          format.html { render json: @page, status: :ok }
          format.json { render json: @page, status: :ok }
        else
          format.html { render json: @page.errors, status: :unprocessable_entity }
          format.json { render json: @page.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /pages/1
    # DELETE /pages/1.json
    def destroy
      @page.destroy
      respond_to do |format|
        format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:name, :path, :content, :site_id, :layout_id, :meta)
    end

    def update_layout
      return if page_params[:content].blank?

      layout_string = page_params[:content].match(/<!--(.*?)-->/).to_a.first
      layout_name = layout_string.gsub("<!--", "").gsub("-->", "").squish.split("=").last + ".html" if layout_string
      layout = Layout.find_by(name: layout_name, site_id: @page.site_id)
      @page.layout_id = layout.id if layout
      @page.save
    end
  end
end

app/controllers/cms/sites_controller.rb
module Cms
  class SitesController < ApplicationController
    before_action :authenticate_admin!

    before_action :set_site, only: [:show, :edit, :edit_cms, :update, :destroy, :add_assets]

    # GET /sites
    # GET /sites.json
    def index
      @sites = Site.all
    end

    # GET /sites/1
    # GET /sites/1.json
    def show
    end

    # GET /sites/new
    def new
      @site = Site.new
    end

    # GET /sites/1/edit
    def edit
    end

    def edit_cms
      @data = {
          site_name: @site.name,
          pages: @site.pages,
          assets: @site.assets.sort { |a,b| a.priority.to_i <=> b.priority.to_i }.reverse,
          layouts: @site.layouts
      }
    end

    # POST /sites
    # POST /sites.json
    def create
      @site = Site.new(site_params)

      respond_to do |format|
        if @site.save
          @site.link_assets_from(site_params[:initialize_with]) if site_params[:initialize_with].present?
          # Make the following redirect to editor path
          format.html { redirect_to site_edit_cms_path(@site), notice: 'Site was successfully created.' }
          format.json { render :show, status: :created, location: @site }
        else
          format.html { render :new }
          format.json { render json: @site.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /sites/1
    # PATCH/PUT /sites/1.json
    def update
      respond_to do |format|
        if @site.update(site_params)
          format.html { redirect_to @site, notice: 'Site was successfully updated.' }
          format.json { render :show, status: :ok, location: @site }
        else
          format.html { render :edit }
          format.json { render json: @site.errors, status: :unprocessable_entity }
        end
      end
    end

    def add_assets
      @asset = @site.assets.new(asset_params)
      @asset.save
    end

    # DELETE /sites/1
    # DELETE /sites/1.json
    def destroy
      @site.assets.delete_all
      @site.pages.delete_all
      @site.layouts.delete_all
      @site.destroy
      respond_to do |format|
        format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id] || params[:site_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(
        :name,
        :domain,
        :description,
        :google_analytics_key,
        :meta, 
        :initialize_with,
        assets: [:attachment]
      )
    end

    def asset_params
      params.require(:assets).permit!
    end
  end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/cms/sites/_form.html.erb
<%= form_with(model: site, local: true) do |form| %>
  <% if site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="card mx-auto mt-3">
      <h5 class="card-header">New Site</h5>
      <div class="card-body">
        <div class="form-row">
          <div class="form-group col-6">
            <%= form.label :name, class: "text-dark" %>
            <%= form.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group col-6">
            <%= form.label :domain, class: "text-dark" %>
            <%= form.text_field :domain, class: "form-control" %>
          </div>

          <% if @site && @site.new_record? %>
            <div class="form-group col-6">
              <%= form.label :initialize_with, class: "text-dark" %>
              <%= form.select(
                :initialize_with,
                ['Bootstrap-4.0', 'Bootstrap-5.0', 'Material-ui-bootstrap'],
                { include_blank: true },
                { class: "form-control" })
              %>
            </div>
          <% end %>

          <div class="form-group col-6">
            <%= form.label :google_analytics_key, class: "text-dark" %>
            <%= form.text_field :google_analytics_key, class: "form-control" %>
          </div>

          <!--<div class="form-group col-12">
            <%= form.label :meta, class: "text-dark" %>
            <%= form.text_area :meta, class: "form-control d-none" %>
            <div id="site_meta_holder"></div>
          </div> -->

          <div class="form-group col-12">
            <%= form.label :description, class: "text-dark" %>
            <%= form.text_area :description, class: "form-control" %>
          </div>

        </div>
      </div>
      <div class="card-footer">
        <%= link_to "Back", sites_path, class: "btn btn-secondary" %>
        <%= form.submit "Submit", class: 'btn btn-dark float-right' %>
      </div>
    </div>
  </div>


  <div class="form-group">
    
  </div>
<% end %>

app/views/cms/sites/add_assets.js.erb
<% if @asset.new_record? %>
  alert("Failed to upload painting: <%= j @asset.errors.full_messages.join(', ').html_safe %>");
<% end %>

app/views/cms/sites/edit.html.erb
<%= render 'form', site: @site %>

app/views/cms/sites/edit_cms.html.erb
<% site_name = @data[:site_name] %>
<% pages = @data[:pages] %>
<% assets = @data[:assets] %>
<% layouts = @data[:layouts] %>

<div class="cms-editor-grid" id="cms-editor-grid">
  <p id="current-site-id" class="d-none"><%= @site.id %></p>
  <div class="row">
    <div class="col-3" id="explorer">
      <ul id="tree">
        <li><a href="#" id="site_name" class="text-white"><%= site_name %></a>
          <ul>
            <li><a href="#">Assets</a>
              <ul>
                <li><a href="#" data-toggle= "modal" data-target= "#AssetFormModal">Bulk Upload Assets</a></li>
                <li><a href="#">Javascripts</a>
                  <ul id="js-ul">
                    <li><%= link_to("New Javascript", new_layout_path, id: "new-js") %></li>
                    <% assets.select { |a| a.kind == "js" } .each do |asset| %>
                      <li class="edit-asset" id="<%= asset.id %>" data-kind="assets" data-toggle= "modal" data-target= "#AssetEditModal">
                        <i class="fab fa-js orange-icon"> </i>
                        <%= link_to asset.name, asset_path(asset), remote: true %>
                      </li>
                    <% end %>
                  </ul>
                </li>

                <li><a href="#">Stylesheets</a>
                  <ul id="css-ul">
                    <li><%= link_to("New CSS", new_layout_path, id: "new-css") %></li>
                    <% assets.select { |a| a.kind == "css" } .each do |asset| %>
                      <li class="edit-asset" id="<%= asset.id %>" data-kind="assets" data-toggle= "modal" data-target= "#AssetEditModal">
                        <i class="fab fa-css3 blue-icon"> </i>
                        <%= link_to asset.name, asset_path(asset), remote: true %>
                      </li>
                    <% end %>
                  </ul>
                </li>

                <li><a href="#">Images</a>
                  <ul>
                    <% assets.select { |a| a.kind == "image" } .each do |asset| %>
                      <li class="edit-asset" id="<%= asset.id %>" data-kind="assets" data-toggle= "modal" data-target= "#AssetEditModal">
                        <i class="far fa-image pink-icon"> </i>
                        <%= link_to asset.name, asset_path(asset), remote: true %>
                      </li>
                    <% end %>
                  </ul>
                </li>
              </ul>
            </li>

            <li><a href="#">Layouts</a>
              <ul id="layouts-ul">
                <li><%= link_to("New Layout", new_layout_path, id: "new-layout") %></li>
                <% layouts.each do |layout| %>
                  <li class="edit-asset" id="<%= layout.id %>" data-kind="layouts" data-toggle= "modal" data-target= "#AssetEditModal">
                    <i class="fab fa-html5 white-icon"> </i>
                    <%= link_to layout.name.gsub('<br>', ''), layout_path(layout), remote: true %>
                  </li>
                <% end %>
              </ul>
            </li>

            <li><a href="#">Pages</a>
              <ul id="pages-ul">
                <li><%= link_to("New Page", new_page_path, id: "new-page") %></li>
                <% pages.each do |page| %>
                  <li class="edit-asset" id="<%= page.id %>" data-kind="pages" data-toggle= "modal" data-target= "#AssetEditModal">
                    <i class="fab fa-html5 white-icon"> </i>
                    <%= link_to page.name.gsub('<br>', ''), page_path(page), remote: true %>
                  </li>
                <% end %>
              </ul>
            </li>

            <li><a href="#">Blogs</a>
              <ul id="blogs-ul">
                <li><%= link_to("New Blog", new_page_path, id: "new-page") %></li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
    </div>

    <div class="col-9" id="preview_content">
      <div id="editor_tabs">
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="AssetFormModal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header p-2">
        <h4 class="modal-title">Upload Assets</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <div class="modal-body p-2">
        <%= form_with(url: :site_add_assets, local: true, remote: true, id: "asset-upload") do |form| %>
          <%= form.hidden_field :site_id, value: @site.id %>
          <div class="custom-file">
              <%= form.label :assets, class: "custom-file-label" %>
              <%= form.file_field :assets, multiple: true, name: "assets[attachment]", class: "custom-file-input" %>
          </div>                    
          </div>
          <div class="modal-body" id="asset-progress">
          </div>
        <% end %>
    </div>
  </div>
</div>

<div class="modal fade" id="AssetEditModal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header p-2">
        <h4 class="modal-title" id="asset-name"></h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <div class="modal-body p-2" id="edit-modal-body">
      </div>
    </div>
  </div>
</div>

<script id="template-upload" type="text/x-tmpl">
<div class="upload">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>

app/views/cms/sites/index.html.erb
<div class="col-12 mt-4 p-5 mb-3 text-white">    
    <h3 class="float-left">Sites</h3>
    <%= link_to 'New Site', new_site_path, class: "float-right btn btn-outline-light" %>    
</div>



<div class="card-columns">
  <% @sites.each do |site| %>
    <div class="card border-0 bg-secondary text-white">
      <%# <img class="card-img-top img-fluid" src="https://place-hold.it/250x100" alt="Card image cap"> %>
      <div class="card-body">
        <h5 class="card-title"><%= site.name %></h5>
        <p class="card-text"><%= site.description %></p>
        <ul class="list-group list-group-flush">
          <li class="list-group-item bg-secondary text-white border-dark">
            <b>Domain:</b>
            <%= site.domain %>
          </li>
          <li class="list-group-item bg-secondary text-white border-dark">
            <b>Google analytics key:</b>
            <%= site.google_analytics_key %>
          </li>
          <li class="list-group-item bg-secondary text-white border-dark">
            <b>Meta Tags:</b>
            <%= site.meta %>
          </li>
        </ul>
        <div class="border"></div>
        <div class="card-body float-right">
          <%= link_to 'Messages', site_messages_path(site), class: "card-link text-white font-weight-bold" %>
          <%= link_to 'Show', site, class: "card-link text-white font-weight-bold" %>
          <%= link_to 'Editor', site_edit_cms_path(site), class: "card-link text-white font-weight-bold", "data-turbolinks": false  %>
          <%= link_to 'Edit', edit_site_path(site), class: "card-link text-white font-weight-bold" %>
          <%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-link text-white font-weight-bold" %>
        </div>
      </div>
    </div>    
  <% end %>
</div>

app/views/cms/sites/new.html.erb
<%= render 'form', site: @site %>

app/views/cms/sites/show.html.erb
<div class="row justify-content-center">
  <div class="col-8">
    <div class="card">
      <div class="card-header font-weight-bold"><h4><%= @site.name %></h4></div>
      <div class="card-body">
        <div class="row">
          <h6 class="font-weight-normal">Domain: <%= @site.domain %></h6>
        </div>
        <div class="row">
          <h6 class="font-weight-normal">Description: <%= @site.description %></h6>
        </div>
        <div class="row">
          <h6 class="font-weight-normal">Tracking key: <%= @site.google_analytics_key.present? ? @site.google_analytics_key : "N/A" %></h6>
        </div>
        <!-- <div class="row">
          <h5>Meta: <pre><%= @site.meta %></pre></h5>
        </div> -->
      </div>
      <div class="card-footer">
        <%= link_to 'Back', sites_path, class: 'btn btn-secondary' %>
        <%= link_to 'Edit', edit_site_path(@site), class: "btn btn-dark float-right" %>
      </div>
    </div>
  </div>
</div>