config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root 'home#index'
  scope :cms, module: 'cms', path: 'cms' do
    resources :assets
    resources :layouts
    resources :pages
    resources :sites do
      get :edit_cms
      post :add_assets
      resources :messages
    end
    post 'custom-assets', to: 'assets#custom_asset'
  end
  match '*path', to: 'home#index', via: :all
end

app/models/layout.rb
class Layout < ApplicationRecord
  has_paper_trail
  belongs_to :site
  has_many :pages
end

app/controllers/cms/layouts_controller.rb
module Cms
  class LayoutsController < ApplicationController
    before_action :authenticate_admin!

    before_action :set_layout, only: [:show, :edit, :update, :destroy]

    # GET /layouts
    # GET /layouts.json
    def index
      @layouts = Layout.all
    end

    # GET /layouts/1
    # GET /layouts/1.json
    def show
      respond_to do |format|
        format.html { render json: { name: @layout.name, content: @layout.content, id: @layout.id } }
        format.js { render :show, status: 200 }
        format.json { render json: { name: @layout.name, content: @layout.content, id: @layout.id } }
      end
    end

    # GET /layouts/new
    def new
      @layout = Layout.new
    end

    # GET /layouts/1/edit
    def edit
    end

    # POST /layouts
    # POST /layouts.json
    def create
      @layout = Layout.find_or_initialize_by(
          name: layout_params[:name].strip.gsub('<br>', ''),
          site_id: layout_params[:site_id]
      )

      respond_to do |format|
        if @layout.update_attributes(layout_params)
          format.json { render json: @layout, status: :created }
        else
          format.json { render json: @layout.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /layouts/1
    # PATCH/PUT /layouts/1.json
    def update
      respond_to do |format|
        if @layout.update(layout_params)
          format.json { render json: @layout, status: :ok }
        else
          format.json { render json: @layout.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /layouts/1
    # DELETE /layouts/1.json
    def destroy
      @layout.destroy
      respond_to do |format|
        format.html { redirect_to layouts_url, notice: 'Layout was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_layout
      @layout = Layout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def layout_params
      params.require(:layout).permit(:name, :content, :site_id)
    end
  end
end

app/helpers/layouts_helper.rb
module LayoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sockem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-dark">
    <% if admin_signed_in? %>
      <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top pt-0">
        <a class="navbar-brand d-flex pl-3" href="/cms/sites" data-turbolinks=false>
          <%= image_tag('cms_logo.png', class: 'img-fluid mx-auto d-block',style: "height:30px;")%>          
          <h6 class="pt-1 pl-2">CMS</h6>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <%= link_to('Logout', destroy_admin_session_path, method: :delete) %>
            </li>          
          </ul>        
        </div>
      </nav>
    <% end %>    
    <div class="container-fluid" id="app">      
      <%= yield %>
    </div>
  </body>
</html>